-- SQL Setup for Centro Comercial SaaS
-- Run this in the Supabase SQL Editor

-- 1. Profiles Table (Extends Auth.Users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  company_name TEXT,
  avatar_url TEXT,
  plan_type TEXT DEFAULT 'free', -- 'free', 'pro', 'enterprise'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Lists Table
CREATE TABLE IF NOT EXISTS lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Prospects Table
CREATE TABLE IF NOT EXISTS prospects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  phone TEXT,
  email TEXT,
  website TEXT,
  instagram TEXT,
  rating DECIMAL,
  reviews_count INTEGER,
  location_json JSONB,
  scraping_source TEXT, -- 'google_maps', 'instagram', etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Prospect Lists Junction (Many-to-Many)
CREATE TABLE IF NOT EXISTS prospect_lists (
  prospect_id BIGINT REFERENCES prospects ON DELETE CASCADE,
  list_id BIGINT REFERENCES lists ON DELETE CASCADE,
  PRIMARY KEY (prospect_id, list_id)
);

-- Enable RLS on everything
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE prospect_lists ENABLE ROW LEVEL SECURITY;

-- Security Policies (Ensure users only see THEIR data)
CREATE POLICY "Users can see own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can edit own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage own lists" ON lists FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own prospects" ON prospects FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own prospect_lists" ON prospect_lists FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM lists WHERE id = prospect_lists.list_id AND user_id = auth.uid()
  )
);
